### ISSUE TITLE
Question about browser compatibility

### ISSUE THREAD

**Issue by raratiru** [nico3333fr/jquery-accessible-hide-show-aria#10]
Hallo,

Thank you for this very useful plugin. 

I would like to ask about cross-browser compatibility. 

Are there any clues about compatibility with mobile browsers for example?

**Comment by nico3333fr** [comment]
Hello,

> Thank you for this very useful plugin. 

You're welcomed :)


> Are there any clues about compatibility with mobile browsers for example?

As it is based on jQuery (and works on 1.x versions), there is no real compatibility issue for JS, except if some devices have problems with jQuery (?).

The compatibilities issues are more on what you use with CSS to animate or display it (see [the demo (see animated)](http://a11y.nicolas-hoffmann.net/hide-show/)), if some devices are not supporting CSS transitions, selector attributes and things like that. 

For exemple, for IE<9, there won't be any transitions. IE6 doesn't support selector attribute like [aria-hidden=true].

As far as I know, mobile devices should not be a problem.

**Comment by raratiru** [comment]
Thank you very much.

There is some great work you have done on ARIA plugins.
