### ISSUE TITLE
Toggle to show all at once

### ISSUE THREAD

**Issue by llahnoraa** [nico3333fr/jquery-accessible-hide-show-aria#12]
Thank you for this very useful plugin!

Is there an option to toggle to open all at once? Same thing for close? That would be very helpful. Thanks!

**Comment by Kozlika** [comment]
I support this idea!

**Comment by nico3333fr** [comment]
Hi there,

sorry for the time I took to do it, but I've just added the option: https://a11y.nicolas-hoffmann.net/hide-show/

Thanks a lot for this idea! 👍
