### ISSUE TITLE
Are anchored link supported?

### ISSUE THREAD

**Issue by llahnoraa** [nico3333fr/jquery-accessible-hide-show-aria#13]
When someone click a link with anchor and take them to another page, is it possible to expand that section open?

**Comment by nico3333fr** [comment]
Hi @llahnoraa 

damn, I've thought to this case with my tabpanel script, but not with this plugin :)
For the moment, there is only an option to make it open by default, see http://a11y.nicolas-hoffmann.net/hide-show/

I'll have a look asap.

**Comment by llahnoraa** [comment]
+1

**Comment by nico3333fr** [comment]
Hi @llahnoraa ,

could you test ? It is okay for me https://a11y.nicolas-hoffmann.net/hide-show/#anims (test with or without it) but I prefer another test. ;)

Cheers,
Nicolas

**Comment by llahnoraa** [comment]
It worked. Looks good to me so far. Can anyone else test on this, such as mobile-wise? 

Do we need to update the plugin file for this?

**Comment by nico3333fr** [comment]
Yes, as you may see in the diff, https://github.com/nico3333fr/jquery-accessible-hide-show-aria/commit/942cd066dad9555164fe4287f86ed04510686356 there are not many differences.

**Comment by llahnoraa** [comment]
Perfect! Thank you for your help on this!
