### ISSUE TITLE
same selector in documentation

### ISSUE THREAD

**Issue by Kozlika** [nico3333fr/jquery-accessible-hide-show-aria#15]
In your documentation page, there is a double same selector (or did I misread?) :

```
/* optional */
.expandmore__button:before,
.expandmore__button:before {
  content : '+ ';
}
```

Anyway, thanks A LOT for this plugin <3

**Comment by nico3333fr** [comment]
No you didn't misread, I was obviously drunk when I did this :)

It is fixed, and you're welcomed. :-*
