### ISSUE TITLE
Define your own classname only once

### ISSUE THREAD

**Issue by rastersysteme** [nico3333fr/jquery-accessible-hide-show-aria#18]
If you want to set your own classname for `$to_expand`, you have to set it twice at the moment:

In _line 16_ you define your var like this: `$to_expand = $('.js-to_expand')`.
In _line 28_ you don’t use this var but instead you use the classname again: `$to_expand = $this.next(".js-to_expand")`.

As expected it would be nice to define your own classname only once inside the vars at the top.

**Comment by nico3333fr** [comment]
Hi @rastersysteme 

you are right. For the moment, I've removed a selector in https://github.com/nico3333fr/jquery-accessible-hide-show-aria/commit/d703cdbb91c53ff753c0975a26ed17a902247aea but I will do better in a next release with a huge rewrite to be more configurable.

Thanks a lot for pointing this out ;)
