### ISSUE TITLE
rails-assets.org compatibility

### ISSUE THREAD

**Issue by padde** [nico3333fr/jquery-accessible-hide-show-aria#19]
Hi,

I was trying to add this package to rails-assets.org for use with the Rails asset pipeline, but it complains with the following error message:

```
jquery-accessible-hide-show-aria has no versions defined. Please create an issue in component's repository.
```

It seems that rails-assets.org will look for the current version Tag in the Git repo. Could you please add the tag for `v1.4.0`? The easiest way to do this would be to create a new Release on Github:

* go to the **Releases** tab
* enter `v1.4.0` for **Tag Version**
* enter Recent commits / `9b7ad41` as **Target**
* you can add a title and description but it's optional
* click **Publish Release**

To check if it works now you can try to add the package to rails-assets.org via https://rails-assets.org/components/new.

Thanks a lot!

**Comment by nico3333fr** [comment]
Hi @padde 

to be honest, I didn't know anything about this :)

Thanks for your help, it is added and the package seems to be ok on rails-assets.org

Kind regards and thanks again,
Nicolas

**Comment by padde** [comment]
Hey Nicolas, thanks for the quick action! :)

Never mind, I am not expecting anyone to know about rails-assets.org. It sure is an obscure piece of technology but I'm stuck with it in some apps I'm currently working on.

Anyway, tagging releases is a good idea in any case, so people visiting the repo know exactly which version they are looking at.

Again, thank you so much and have a great day!

**Comment by nico3333fr** [comment]
Hi @padde 

I was testing it for another repo https://github.com/nico3333fr/van11y-accessible-hide-show-aria/releases/tag/V1.0.3 but it says that there is no version defined, even if I have made a release. Do you know why ?

Kind regards,
Nicolas

**Comment by padde** [comment]
@nico3333fr hi, It seems that the convention is to use a lowercase `v` as the first character in the tag. Maybe that is the problem?

**Comment by nico3333fr** [comment]
@padde correct, thanks a lot :)
