### ISSUE TITLE
Prefix JS hooks with js-

### ISSUE THREAD

**Issue by kaelig** [nico3333fr/jquery-accessible-hide-show-aria#2]
Classes used as DOM hooks for the JS (and not for styling) should be differentiated. Usually it's done by prefixing these classes with `js-`, but you could also use `data-js-xxx` or `data-xxx-js` attributes which would have the same effect.

**Comment by nico3333fr** [comment]
Thanks a lot for this suggestion :+1: 

<img src="http://ljdchost.com/lDAA1B8.gif" alt="Yeah" />
