### ISSUE TITLE
Why attach to element vs using button directly in HTML?

### ISSUE THREAD

**Issue by runnickrun** [nico3333fr/jquery-accessible-hide-show-aria#25]
A quick question: what's the benefit of generating <button> and adding it to element in jquery vs  using <button> directly in HTML? Is it because for accessibility?

**Comment by nico3333fr** [comment]
Not exactly, it is for progressive enhancement: if JS fails to load or is broken, the HTML structure will allow the user to browse the page without any problem. 
If we put directly the button and the JS fails, there will be a button, but that doesn't do anything.
