### ISSUE TITLE
One button to collapse/expand them all - keyboard issue

### ISSUE THREAD

**Issue by llahnoraa** [nico3333fr/jquery-accessible-hide-show-aria#29]
I noticed the "Expand all" button doesn't work on keyboard properly. 

If you hit Enter, it doesn't do anything.

If you hit Spacebar, it sort of worked but not working as expected. 

The mouse click state is fine though.

You can test the "expand all" button on your page: https://a11y.nicolas-hoffmann.net/hide-show/

**Comment by nico3333fr** [comment]
The website is updated and the script fixed, thanks for spotting this ;)
