### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by kaelig** [nico3333fr/jquery-accessible-hide-show-aria#3]
To ensure that:
- attributes are added, classes are there, and the correct elements are being added too.
- JS interactions are fired correctly

With [Karma](http://karma-runner.github.io/0.12/index.html), for example.

And then automate these tests using [Travis](https://travis-ci.org/), enabling you to see if other developers' contributions pass the tests, as in this screenshot:

![screenshot 2015-02-05 14 34 12](https://cloud.githubusercontent.com/assets/85783/6061973/143fbab0-ad44-11e4-89c9-55fabf7763db.png)

**Comment by kaelig** [comment]
Closing this as it is stale and I'm cleaning up my issues.

**Comment by nico3333fr** [comment]
Hi @kaelig 

Yes, I did let it opened, however, I've not enough time for the moment, but it is noted and it will be added anyway.

Thanks again 👍
