### ISSUE TITLE
Action sur un élément qui n'est pas dans le même conteneur (mais dans le même parent)

### ISSUE THREAD

**Issue by davidpollet** [nico3333fr/jquery-accessible-hide-show-aria#4]
Salut Nico,
Je souhaites utiliser ton plugin sur mon futur blog. A coté du titre, je souhaite mettre le boutton expandmore__button pour afficher le chapo de l'article. Le soucis, c'est que le bouton n'est pas dans le même conteneur que le texte caché. En revanche, il est dans le même parent.

C'est possible de faire ça ou faut obbligatoirement que mon bouton soit dans le même conteneur ?

J'ai essayé de bricoler avec une position absolute mais c'est pas bô. ^^

**Comment by davidpollet** [comment]
Edit en cours, j'ai fait une fausse manip. :p

**Comment by nico3333fr** [comment]
Hello,

en l'état actuel des choses, la seule contrainte est que les éléments js-expandmore et js-to_expand soient adjacents, vu que j'utilise $this.next. Si c'est le cas, ça fonctionnera.

Sinon il faudrait que je trouve un système qui permette de trouver "le prochain". Note que cela doit pouvoir se faire, il suffirait de changer la méthode 

```
$to_expand = $this.next(".js-to_expand"),
```
en qqch comme 
```
$to_expand = $this.parent().find(".js-to_expand"),
```

et cela devrait marcher.

à+
Nico

**Comment by davidpollet** [comment]
Salut Nico,
Merci pour ta réponse. J'ai testé $this.parent mais ça ne fonctionne pas. 
Du coup, j'ai adapté ma mise en page pour garder mon boutton dans le même conteneur puis j'ai joué avec une position absolute qui fonctionne bien grâce à ma réorganisation graphique.
Le seul point qui me gène un peu, c'est que  le boutton ne sera pas au bon endroit pour les lecteurs d'écran mais je vais pas faire la fine bouche.
L'essentiel est que ça tienne la route et que tout le monde aient accès à la fonctionnalité ce que je souhaite --> cacher le chapo de l'article.

Autre chose aussi, ce serait cool de pouvoir jouer avec les animations css si possible.
Pour l'instant, j'arrive à jouer une animation au déclenchement invisible --> visible grâce à :not([aria-hidden="true"]) mais ça coince pour jouer dans l'autre sens. 
Je ne pense pas que ce soit possible en pur css d'ailleurs étant donné le contexte.

Peut être ajouté les class .is-opened & .is-closed sur .js-to_expand rendrait les choses plus simple. Je n'ai pas (encore) les compétences pour intervenir sur ton code.

En tout cas merci pour tes plugins !
a+

**Comment by nico3333fr** [comment]
Salut,

donne-moi un exemple de structure pour ton code, et je te dirais ce qui fonctionne (le $this.parent ne peut pas marcher)

Pour les animations, faudrait que je fasse qq essais, ça doit bien être possible en animant max-height ou qqch dans le genre ^^

à+

**Comment by davidpollet** [comment]
Salut Nico,

li.article
____.container
________figure.article_thumb
________.article-description
________.article_related
____________.article_preview-action.js-expandmore
____________.article_link
____________.article_totalcomments
____.article-preview.js-to_expend

Pour l'animation css, j'ai fait : 
@keyframes expand {
  0% {
    opacity: 0;
    transform: scale(0);
    transform-origin: right top;
  }
  100% {
    opacity: 1;
    transform: scale(1);
    transform-origin: right top;
  }
}

.article_preview:not([aria-hidden="true"]) {
    animation: expand 300ms;
 }

C'est pour le retour à [aria-hidden="true"] que ça se complique mais d'un point vue UX, ça ne me choque pas. :)

**Comment by nico3333fr** [comment]
Du coup, ça donnerait :

```
$to_expand = $this.parents(".article").find(".js-to_expand"),
```

Je regarde pour les animations dès que j'ai un peu de temps. ;)

**Comment by davidpollet** [comment]
Salut Nico,
Merci pour l'info.
J'ai fait l'fou fou avec ton plugin. Mon blog ressemble à une armoire Ikéa. Il y a des tirroirs partout. :d 
Si tu veux, je te montre quand c'est prêt. ;)

**Comment by nico3333fr** [comment]
Salut,

pas de souci, je suis curieux de voir ça :)

à+
Nico
